### PR TITLE
Updating the blog for personal use.

### PR DESCRIPTION
**Pull request by Piyush811999**

### CODE REVIEW

**Comment by Piyush811999** [comment]
Please ignore this, raised by mistake, this was supposed to go into my main branch.

**Comment by cassidoo** [comment]
Oop! Mind sharing a link to your blog when you're done?

**Comment by Piyush811999** [comment]
Sure!

**Comment by Piyush811999** [comment]
Hi @cassidoo, my blog is now live (and in a presentable state) at [piyushmakwana.in](https://piyushmakwana.in/posts/). Also, I wanted to say that your blog has been inspiration towards the kind of blog I wanted to make. And thank you for making it open source; otherwise, I don't know how long I would've procrastinated in creating my own :D.

**Pull request closed without merging**
